services:
  api:
    build: ./backend
    container_name: backend_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - ENV=development

  web:
    build: ./frontend
    container_name: frontend_web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8000